Hackathon/Hackathon/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tech_army.urls')),
    path('myapp', include('tech_army.urls')),
]

Hackathon/tech_army/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name='tech_army'
urlpatterns = [
    
path('', views.Noticeboard,name='index1'),
path('index', views.Noticeboard,name='index'),
path('signup', views.signup, name='signup'),
path('login', views.login_view, name='login'),
path('logged', views.logged, name='logged'),
path('logged1', views.logged1, name='logged1'),
path('profile/', views.update_user_id, name='profile'),
path('update_user_id', views.update_user_id, name='update_user_id'),
path('products/<str:municipality_name>/',views.shared_textarea,name='products'),
path('shared_textareas', views.shared_textareas, name='shared_textareas'),
path('shared_textareasdep', views.shared_textareasdep, name='shared_textareasdep'),
path('reply_textarea', views.ReplyForms, name='reply_textarea'),
path('emergency', views.emergency, name='emergency'),
path('deplogin', views.login_view_dept, name='deplogin'),
path('update_activity', views.update_activity, name='update_activity'),
path('municipality1', views.municipality1, name='municipality1'),
path('municipality2', views.municipality2, name='municipality2'),
path('municipality3', views.municipality3, name='municipality3'),
path('municipality4', views.municipality4, name='municipality4'),
path('showsolnonly', views.showsolnonly, name='showsolnonly'),
path('warning', views.warning, name='warning'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hackathon/tech_army/models.py
from django.db import models
from django.contrib.auth.models import User



class Society(models.Model):
    place_id=models.AutoField
    municipality_name=models.CharField(max_length=50)
    ward_no=models.CharField(max_length=50)
    desc=models.CharField(max_length=500)
    
    def __str__(self):
           return self.municipality_name
       
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    citizenship_id = models.CharField(max_length=20,default="")
    municipality_name=models.CharField(max_length=50)
    ward_no=models.CharField(max_length=50)
    image = models.ImageField(upload_to='tech_army/images',default="")
    

    def __str__(self):
        return self.user.username

class SharedTextarea(models.Model):
    content = models.TextField()
    title = models.TextField(default="")
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
class Reply(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.TextField(default="")
class Notice(models.Model):
    title = models.TextField(default="")
    content = models.TextField()
class Activity(models.Model):
    title = models.TextField(default="")
    image = models.ImageField(upload_to='tech_army/images',default="")
    
class Municipality1(models.Model):
   content = models.CharField(max_length=50)
   image = models.ImageField(upload_to='tech_army/images',default="")
   location = models.CharField(max_length=50)
   ward_no=models.CharField(max_length=50)
   
class Municipality2(models.Model):
    
   content = models.CharField(max_length=50)
   image = models.ImageField(upload_to='tech_army/images',default="")
   location = models.CharField(max_length=50)
   ward_no=models.CharField(max_length=50)
    
class Municipality3(models.Model):
    
   content = models.CharField(max_length=50)
   image = models.ImageField(upload_to='tech_army/images',default="")
   location = models.CharField(max_length=50)
   ward_no=models.CharField(max_length=50)
class Municipality4(models.Model):
    
   content = models.CharField(max_length=50)
   image = models.ImageField(upload_to='tech_army/images',default="")
   location = models.CharField(max_length=50)
   ward_no=models.CharField(max_length=50)
    
    
    
    
    
    
class Department(models.Model):
    name = models.TextField(default="")
    citizenship_no = models.TextField()

Hackathon/tech_army/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile
from .models import Activity

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['title', 'image']



class Signup(UserCreationForm):
   
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)
    
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
class UserIDForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('user','citizenship_id','municipality_name','ward_no','image')

    user = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your student ID',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    citizenship_id = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your student ID',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    municipality_name= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your student ID',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    ward_no = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your student ID',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
class SharedTextareaForm(forms.Form):
    title = forms.CharField(widget=forms.Textarea(attrs={'class':'resize-none h-10 p-1 w-full my-3  border rounded-lg focus:outline-none focus:ring focus:border-blue-500'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'resize-none h-16 w-full my-3  border rounded-lg focus:outline-none focus:ring focus:border-blue-500'}))
    
class ReplyForm(forms.Form):
    title = forms.CharField(widget=forms.Textarea(attrs={'class':'resize-none h-10 p-1 w-full my-3  border rounded-lg focus:outline-none focus:ring focus:border-blue-500'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'resize-none h-16 w-full my-3  border rounded-lg focus:outline-none focus:ring focus:border-blue-500'}))
  
    
from django import forms

class DeptloginForm(forms.Form):
    user = forms.CharField(label='Department User', max_length=100)
    citizenship_no = forms.CharField(label='Citizenship Number', max_length=10)

Hackathon/tech_army/views.py
from django.shortcuts import render, redirect
from .forms import Signup, LoginForm, UserIDForm, SharedTextareaForm, ReplyForm,DeptloginForm
from .models import Society, UserProfile, SharedTextarea, Reply,Notice,Activity,Municipality1,Municipality2,Municipality3,Municipality4
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import nltk
from django.contrib.auth import authenticate, login
from django.db import IntegrityError
nltk.download('stopwords')
stemmer = nltk.SnowballStemmer("english")
from nltk.corpus import stopwords
import string
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Activity
from .forms import ActivityForm
stopwords = set(stopwords.words('english'))

with open('tech_army/mnb.pkl', 'rb') as file:
    mnb_model = pickle.load(file)

with open('tech_army/count.pkl', 'rb') as file:
    count_vectorizer = pickle.load(file)

with open('tech_army/tfidf.pkl', 'rb') as file:
    tfidf = pickle.load(file)


def clean_text(text):
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    words = [word for word in text.split(' ') if word not in stopwords]
    words = [stemmer.stem(word) for word in words]
    return " ".join(words)


def detect_hate_speech(text):
    # Preprocess the text and convert it to a bag-of-words representation.
    text_vectorized = count_vectorizer.transform([text])
    text_tfidf = tfidf.transform(text_vectorized)

    # Make predictions using the MNB model.
    prediction = mnb_model.predict(text_tfidf)

    return prediction[0]


def index(request):
    return render(request, 'base.html')


def signup(request):
    if request.method == 'POST':
        form = Signup(request.POST)
        if form.is_valid():
            user = form.save()
            try:
                user_profile = UserProfile.objects.create(user=user)
            except IntegrityError:
                pass
            return redirect('/login')
    else:
        form = Signup()

    return render(request, 'signup.html', {'form': form})


# def login_view(request):
#     if request.method == 'POST':
#         form = LoginForm(request, data=request.POST)
#         if form.is_valid():
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password')
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('/logged')
#         return redirect('/logged')
#     else:
#         form = LoginForm()
#     return render(request, 'login.html', {'form': form})   
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            # Check if the user account exists
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                user = None

            if user is not None:
                # Authenticate the user
                user = authenticate(request, username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('/logged')  # Redirect to the logged-in user's dashboard or home page
                else:
                    # Authentication failed, handle the error (e.g., show an error message)
                    pass
            else:
                # User account does not exist, handle the error (e.g., show an error message)
                pass
        else:
            # Form is not valid, handle the error (e.g., show an error message)
            pass
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

def login_view_dept(request):
    if request.method == 'POST':
        form = DeptloginForm(request.POST)
        if form.is_valid():
           
            return redirect('/logged1')  # Redirect to the desired URL after successful login
           
    else:
        form = DeptloginForm()

    return render(request, 'deptlogin.html', {'form': form })

def logged1(request):
    
    return render(request, 'logged1.html',)        
        
        
        
        
@login_required
def logged(request):
    products = Society.objects.all()
    params = {'product': products}
    return render(request, 'logged.html', params)


@login_required
def update_user_id(request):
    user = request.user

    try:
        user_profile = UserProfile.objects.get(user=user)
    except UserProfile.DoesNotExist:
        user_profile = UserProfile.objects.create(user=user)

    if request.method == 'POST':
        form = UserIDForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('/update_user_id')
    else:
        form = UserIDForm(instance=user_profile)

    return render(request, 'studentid.html', {'form': form, 'user_profile': user_profile})


def shared_textarea(request,municipality_name):
    user = request.user
    try:
        user_profile = UserProfile.objects.get(user=user)
        

        if user_profile.municipality_name == municipality_name :
    
            form = SharedTextareaForm()
            entries = SharedTextarea.objects.all()
            user_profiles = UserProfile.objects.all()
            params = {'user_profiles': user_profiles}

            if request.method == 'POST':
                form = SharedTextareaForm(request.POST)
                if form.is_valid():
                    content = form.cleaned_data['content']
                    title = form.cleaned_data['title']
                    # Perform hate speech detection using the MNB model.
                    text_clean = clean_text(content)  # Preprocess the text and get a list of words.
                    print(text_clean)
                    hate_speech_prediction = detect_hate_speech(text_clean)
                    print(hate_speech_prediction)

                    if hate_speech_prediction == 1:
                        return redirect('/logged')  # Make sure you have an 'index' view to handle this redirection.
                        # Handle hate speech (e.g., display an error message or take appropriate action).
                        # You may want to show an error message here.

                    shared_textarea = SharedTextarea.objects.create(content=content, title=title, user=request.user)
                    shared_textarea.user_profile = UserProfile.objects.get(user=request.user)
                    shared_textarea.save()
                    return redirect('/shared_textareasdep')
        
            return render(request, 'shared_textarea.html', {'form': form, 'entries': entries, 'params': params, 'username': request.user.username})
   
        else:
            return redirect('/shared_textareasdep')
            
        
    except UserProfile.DoesNotExist:
       pass
def ReplyForms(request):
    form = ReplyForm()
    entries = Reply.objects.all()
    user_profiles = UserProfile.objects.all()
    params = {'user_profiles': user_profiles}

    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            title = form.cleaned_data['title']
            shared_textarea = Reply.objects.create(content=content, title=title, user=request.user)
            shared_textarea.user_profile = UserProfile.objects.get(user=request.user)
            shared_textarea.save()
            return redirect('/reply_textarea')

    return render(request, 'reply_textarea.html', {'form': form, 'entries': entries, 'params': params, 'username': request.user.username})
def showsolnonly(request):
    form = ReplyForm()
    entries = Reply.objects.all()
    user_profiles = UserProfile.objects.all()
    params = {'user_profiles': user_profiles}

    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            title = form.cleaned_data['title']
            shared_textarea = Reply.objects.create(content=content, title=title, user=request.user)
            shared_textarea.user_profile = UserProfile.objects.get(user=request.user)
            shared_textarea.save()
            return redirect('/reply_textarea')

    return render(request, 'viewsoln.html', {'form': form, 'entries': entries, 'params': params, 'username': request.user.username})



def Noticeboard(request):
    product1 = Notice.objects.all()
    params1 = {'product1': product1}
    product2 = Activity.objects.all()
    params2 = {'product2': product2}
    context = {**params1, **params2}
    return render(request, 'base.html', context)


def emergency(request):
    
      return render(request, 'emergency.html')




def shared_textareas(request):
    
            form = SharedTextareaForm()
            entries = SharedTextarea.objects.all()
            user_profiles = UserProfile.objects.all()
            params = {'user_profiles': user_profiles}

            if request.method == 'POST':
                form = SharedTextareaForm(request.POST)
                if form.is_valid():
                    content = form.cleaned_data['content']
                    title = form.cleaned_data['title']
                    # Perform hate speech detection using the MNB model.

Hackathon/tech_army/templates/logged.html
{% extends 'base.html' %}
{% block content%}
<div class="flex justify-center space-x-5 mb-4">
  <a href="{% url 'tech_army:municipality1'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore Kathmandu
    </button>
  </a> 
  <a href="{% url 'tech_army:municipality2'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore Budhanilkantha
    </button>
  </a> 
  <a href="{% url 'tech_army:municipality3'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore Kirtipur
    </button>
  </a> 
  <a href="{% url 'tech_army:municipality4'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore Tokha
    </button>
  </a> 
  
</div>



<div class="grid grid-cols-1 md:grid-cols-2 m-3 lg:grid-cols-3 gap-8">
    {% for i in product %}
    <div class="bg-blue-100 rounded-lg shadow-md p-4 w-120 h-100 hover:bg-red-100">
      
     
      <h2 class="text-xl font-bold mb-2">Name:{{ i.municipality_name }}</h2>
      <h2 class="text-xl font-semibold mb-2">Ward_no:{{ i.ward_no }}</h2>
      <h2 class="text-xl font-semibold mb-2">Description:{{ i.desc}}</h2>

      
      <a href="{% url 'tech_army:products' i.municipality_name %}"> 
        <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
          Enter area
        </button>
      </a> 
      
    </div>
    

    {% endfor %}
  </div>
  




{% endblock%}

Hackathon/tech_army/templates/logged1.html
{% extends 'base.html' %}
{% block content%}

<a href="{% url 'tech_army:shared_textareasdep'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Enter area
    </button>
  </a> 
  <a href="{% url 'tech_army:update_activity'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Update Activity
    </button>
  </a> 
  <a href="{% url 'tech_army:municipality1'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore1
    </button>
  </a> 
  <a href="{% url 'tech_army:municipality2'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore2
    </button>
  </a> 
  <a href="{% url 'tech_army:municipality3'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore3
    </button>
  </a> 
  <a href="{% url 'tech_army:municipality4'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Explore4
    </button>
  </a> 
{% endblock%}

Hackathon/tech_army/templates/logged2.html
{% extends 'base.html' %}
{% block content%}


<h2>Previous Problems:</h2>
  {% for entry in entries %}
  <p>{{ entry.user.username}}</p>
    <p>{{ entry.content }}</p>
    <p>{{ entry.created_at }}</p>
    <p>{{ entry.title }}</p>
    <hr>
  {% empty %}
    <p>No previous entries found.</p>
  {% endfor %}
  <a href="{% url 'tech_army:showsolnonly'  %}"> 
    <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
      Show solutions
    </button>
  </a> 
  {% endblock%}

Hackathon/tech_army/templates/login.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock%}
{% block content%}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action="{% url 'tech_army:login' %}">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>


        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

       
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 mt-20 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

Hackathon/tech_army/templates/mun1.html
{% extends 'base.html' %}
{% block content%}
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    {% for i in product %}
    <div class="bg-white rounded-lg shadow-md p-4 w-120 h-100 hover:bg-blue-100">
      
        <img src="{{ i.image.url }}" alt="" class="w-100 h-40 object-cover rounded-lg mb-4  flex  items-center justify-center">
        <h2 class="text-xl font-semibold mb-2">{{ i.content }}</h2>
        <h2 class="text-xl font-semibold mb-2">{{ i.location }}</h2>
        <h2 class="text-xl font-semibold mb-2">{{ i.ward_no }}</h2>
      
      {% comment %} <a href="{% url 'tech_army:products' i.municipality_name %}"> 
        <button class="bg-red-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-5">
          Enter area
        </button>
      </a>  {% endcomment %}
    </div>
    

    {% endfor %}
  </div>
  
  
  
  




{% endblock%}

Hackathon/tech_army/templates/mun2.html
{% extends 'base.html' %}
{% block content%}
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    {% for i in product %}
    <div class="bg-white rounded-lg shadow-md p-4 w-120 h-100 hover:bg-blue-100">
      
        <img src="{{ i.image.url }}" alt="" class="w-100 h-40 object-cover rounded-lg mb-4  flex  items-center justify-center">
        <h2 class="text-xl font-semibold mb-2">{{ i.content }}</h2>
        <h2 class="text-xl font-semibold mb-2">{{ i.location }}</h2>
        <h2 class="text-xl font-semibold mb-2">{{ i.ward_no }}</h2>
      
      
    </div>
    

    {% endfor %}
  </div>
  
  
  
  




{% endblock%}

Hackathon/tech_army/templates/mun3.html
{% extends 'base.html' %}
{% block content%}
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    {% for i in product %}
    <div class="bg-white rounded-lg shadow-md p-4 w-120 h-100 hover:bg-blue-100">
      
        <img src="{{ i.image.url }}" alt="" class="w-100 h-40 object-cover rounded-lg mb-4  flex  items-center justify-center">
        <h2 class="text-xl font-semibold mb-2">{{ i.content }}</h2>
        <h2 class="text-xl font-semibold mb-2">{{ i.location }}</h2>
        <h2 class="text-xl font-semibold mb-2">{{ i.ward_no }}</h2>
      
      
    </div>
    

    {% endfor %}
  </div>
  
  
  
  




{% endblock%}

Hackathon/tech_army/templates/reply_textarea.html
{% extends 'base.html' %}
{% comment %} {% block content%}
<!DOCTYPE html>
<html>
<head>
  <title>Shared Textarea</title>
</head>
<body>
  <form method="POST" action="{% url 'tech_army:reply_textarea'  %}" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
  
  <hr>
  
  <h2>Previous Entries:</h2>
  {% for entry in entries %}
  <p>{{ entry.user.username}}</p>
  <p>{{ entry.title }}</p>
    <p>{{ entry.content }}</p>
    <p>{{ entry.created_at }}</p>
    <hr>
  {% empty %}
    <p>No previous entries found.</p>
  {% endfor %}
</body>
{% endblock %}
</html>   {% endcomment %}

{% comment %} {% extends 'base.html' %} {% endcomment %}
{% block content%}
<!DOCTYPE html>
<html>

<head>
  <title>Shared Textarea</title>
</head>

<body>
  <h1 class="text-center font-medium text-4xl mt-8 text-indigo-700">List of Possible Solutions</h1>
  <div class="mx-auto  p-4">
    <div class="max-w-lg mx-auto bg-white rounded-sm shadow-md p-8">
      <div class="flex items-center justify-center rounded-xl bg-indigo-100 p-3 m-auto">
        <form method="POST" action="{% url 'tech_army:reply_textarea'  %}">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 w-full rounded-md mt-4">Submit</button>
        </form>
      </div>
    </div>
      
      <hr class="my-6">

      <h2 class="text-xl  font-bold text-center">Previous Entries:</h2>
      <div class=" flex flex-row flex-wrap justify-center space-y-4 space-x-4 mt-4">
        {% for entry in entries %}
        <div class="border p-4 my-4 w-1/4 bg-blue-200 rounded-md">
          <p class="text-lg font-semibold">{{ entry.user.username}}</p>
          <p class="text-gray-800">{{ entry.title }}</p>
          <p class="text-gray-500">{{ entry.content }}</p>
          <p class="text-blue-500">{{ entry.created_at }}</p>
          
        </div>
        <hr>
        {% empty %}
        <p>No previous entries found.</p>
        {% endfor %}

        {% endblock %}
      </div>
    </div>
</body>

</html>